#version 450
#extension GL_GOOGLE_include_directive : require

layout(local_size_x = 256, local_size_y = 1, local_size_z = 1) in;

// ----- include -----
#include "../common/buffer_structures.inc"
// -------------------

layout(std430, set = 0, binding = 0) readonly buffer AstarPath { ivec4 astar_path[]; };
layout(std430, set = 0, binding = 1) buffer MaxUnimpendedPathIndices { uint max_unimpended_path_indices[]; };
layout(std430, set = 0, binding = 2) coherent buffer ChunkHashTable { HashTableCounters chunk_hash_table_counters; ChunkHashTableSlot chunk_hash_table_slots[]; };
layout(std430, set = 0, binding = 3) readonly buffer ChunkVoxels { VoxelData voxels[]; };

layout(push_constant) uniform FindUnimpendedPathsPushConstants {
    ivec4 u_chunk_dim;

    uint u_exclusive_window_size; // Количество точек в окне, но кроме текущей точки
    uint u_start_id;
    uint u_max_step_height;
    uint u_count_astar_points;

    uint u_chunk_hash_table_size;
    uint u_voxels_per_chunk;
    uint u_pack_offset;
    uint u_pack_bits;
};

// ----- include -----
#include "../voxel_grid/chunk_pool/read_voxels.inc"
// -------------------

int abs_i(int v) {
    return v < 0 ? -v : v;
}

int sign_i(int v) {
    return v < 0 ? -1 : (v > 0 ? 1 : 0);
}

bool is_wall_voxel(ivec3 pos) {
    return voxel_vis(pos) == 1u;
}

// Если будет result > abs(max_offset) -> спуститься/подняться не получилось 
int voxel_y_offset(ivec3 pos, uint max_offset_u) {
    int max_offset = int(max_offset_u);

    // Если целевая позиция внутри стены/земли — пытаемся подняться вверх,
    // пока не найдём воздух.
    if (is_wall_voxel(pos)) {
        for (int dy = 1; dy <= max_offset; dy++) {
            ivec3 stand_pos = pos + ivec3(0, dy, 0);

            if (!is_wall_voxel(stand_pos)) {
                return dy;
            }
        }

        return max_offset + 1;
    }

    // Если целевая позиция в воздухе — пытаемся найти землю под ногами.
    for (int drop = 0; drop <= max_offset; drop++) {
        ivec3 stand_pos = pos + ivec3(0, -drop, 0);
        ivec3 ground_pos = stand_pos + ivec3(0, -1, 0);

        if (!is_wall_voxel(stand_pos) && is_wall_voxel(ground_pos)) {
            return -drop;
        }
    }

    return -(max_offset + 1);
}

bool try_make_step(ivec3 pos, ivec2 step_dir_xz, out ivec3 next) {
    next = pos + ivec3(step_dir_xz.x, 0, step_dir_xz.y);

    int y_offset = voxel_y_offset(next, u_max_step_height);

    if (abs_i(y_offset) <= int(u_max_step_height)) {
        next.y += y_offset;
        return true;
    }

    next = pos;
    return false;
}

bool make_step(inout ivec3 current_pos, ivec2 step_dir_xz) {
    ivec3 next;

    if (!try_make_step(current_pos, step_dir_xz, next)) {
        return false;
    }

    current_pos = next;
    return true;
}

bool is_path_unimpended(ivec3 from_pos, ivec3 to_pos) {
    if (is_wall_voxel(from_pos))
        return false;
    
    ivec3 diff = to_pos - from_pos;

    ivec3 current_pos = from_pos;

    ivec3 sign_dir = ivec3(sign_i(diff.x), sign_i(diff.y), sign_i(diff.z));
    ivec3 abs_diff = ivec3(abs_i(diff.x), abs_i(diff.y), abs_i(diff.z));

    ivec3 abs_offset = ivec3(0, 0, 0);
    
    int max_steps = abs_diff.x + abs_diff.z;
    int max_possible_height_delta = max_steps * int(u_max_step_height);

    if (abs_i(diff.y) > max_possible_height_delta)
        return false;

    while (abs_offset.x < abs_diff.x || abs_offset.z < abs_diff.z) {
        if (abs_diff.x == 0) {
            if (!make_step(current_pos, ivec2(0, sign_dir.z)))
                return false;

            abs_offset.z++;
        } else if (abs_diff.z == 0) {
            if (!make_step(current_pos, ivec2(sign_dir.x, 0)))
                return false;

            abs_offset.x++;
        } else {
            int lhs = (2 * abs_offset.x + 1) * abs_diff.z;
            int rhs = (2 * abs_offset.z + 1) * abs_diff.x;

            if (lhs < rhs) {
                if (!make_step(current_pos, ivec2(sign_dir.x, 0)))
                    return false;

                abs_offset.x++;
            } else if (lhs > rhs) {
                if (!make_step(current_pos, ivec2(0, sign_dir.z)))
                    return false;

                abs_offset.z++;
            } else {
                ivec3 next;

                if (try_make_step(current_pos, ivec2(sign_dir.x, 0), next) && 
                    make_step(next, ivec2(0, sign_dir.z)))
                {
                    // Удалось пробраться в угол
                     current_pos = next;
                     abs_offset += ivec3(1, 0, 1);
                     continue;
                }

                if (try_make_step(current_pos, ivec2(0, sign_dir.z), next) && 
                    make_step(next, ivec2(sign_dir.x, 0)))
                {
                    // Удалось пробраться в угол
                     current_pos = next;
                     abs_offset += ivec3(1, 0, 1);
                     continue;
                }

                return false; // Не удалось пробраться двумя способами
            }
        }
    }

    return current_pos.y == to_pos.y;
}

void main() {
    uint from_local_id = gl_GlobalInvocationID.x;

    uint window_index = gl_GlobalInvocationID.y;
    uint window_offset = window_index + 1u;

    if (window_index >= u_exclusive_window_size) return;

    uint from_id = u_start_id + from_local_id;
    uint to_id = from_id + window_offset;

    if (from_id >= u_count_astar_points) return;

    atomicMax(max_unimpended_path_indices[from_id], from_id);

    if (to_id >= u_count_astar_points) {
        return;
    }
    
    ivec3 from_pos = astar_path[from_id].xyz;
    ivec3 to_pos = astar_path[to_id].xyz;

    if (is_path_unimpended(from_pos, to_pos)) {
        atomicMax(max_unimpended_path_indices[from_id], to_id);
    }
}
