#ifndef CHUNK_HASH_TABLE_GET_OR_CREATE_GLSL
#define CHUNK_HASH_TABLE_GET_OR_CREATE_GLSL

#include "common.inc"
#include "config_functions/chunk_key_inc.inc"
#include "config_functions/init_chunk_meta.inc"
#include "config_functions/pop_free_chunk_id.inc"

#include "config_begin.inc"
#include "../../common/hash_table/hash_table_get_or_create_impl.inc"
#include "config_end.inc"

#endif // CHUNK_HASH_TABLE_GET_OR_CREATE_GLSL
