#ifndef COUNTER_HASH_TABLE_GET_OR_CREATE
#define COUNTER_HASH_TABLE_GET_OR_CREATE

#include "common.inc"
#include "../../voxel_grid/chunk_hash_table/config_functions/chunk_key_comp.inc"
#include "config_functions/counter_alloc_meta_init.inc"

#include "config_begin.inc"
// #include "../../common/hash_table/hash_table_get_or_create_impl.inc"
#include "hash_table_get_or_create_impl_temp.inc"
#include "config_end.inc"

#endif
