#version 460

layout(local_size_x = 16, local_size_y = 16) in;

layout(set = 0, binding = 0) uniform UniformBufferObject {
    uint image_width;
    uint image_height;
    vec4 color;
} ubo;

layout(set = 0, binding = 1, rgba8) uniform writeonly image2D output_texture;

void main()
{
    uvec2 pixel = gl_GlobalInvocationID.xy;

    if (pixel.x >= ubo.image_width || pixel.y >= ubo.image_height) {
        return;
    }

    imageStore(output_texture, ivec2(pixel), ubo.color);
}
