#version 460
#extension GL_GOOGLE_include_directive : require

layout(local_size_x = 256) in;

#include "common/hash_table/hash_table_decl.inc"
#include "common/utils.inc"
#include "voxel_point_map/index_hash_table/decl.inc"

layout(set = 0, binding = 0) uniform ParamsBuffer {
    uint num_hash_table_slots;
} params;

layout(std430, set = 0, binding = 2) buffer MapPointCountBuffer {
    uint count;
} map_point_count_buffer;

layout(std430, set = 0, binding = 4) coherent buffer PointHashTable {
    HashTableCounters point_hash_table_counters;
    IndexHashTableSlot point_hash_table_slots[];
};

#define HT_PREFIX point_hash_table
#define SLOT_VALUE_TYPE uint
#define SLOT_KEY_TYPE uvec2
#define SLOT_TYPE IndexHashTableSlot
#define TABLE_COUNTERS point_hash_table_counters
#define SLOTS_BUFFER point_hash_table_slots
#define HASH_TABLE_SIZE params.num_hash_table_slots
#define KEY_HASH_FUNC hash_uvec2
#define MAX_CAS_ATTEMPTS 5u

#include "common/hash_table/hash_table_common_impl.inc"

#undef HT_PREFIX
#undef SLOT_VALUE_TYPE
#undef SLOT_KEY_TYPE
#undef SLOT_TYPE
#undef TABLE_COUNTERS
#undef SLOTS_BUFFER
#undef HASH_TABLE_SIZE
#undef KEY_HASH_FUNC
#undef MAX_CAS_ATTEMPTS

void main()
{
    uint id = gl_GlobalInvocationID.x;

    if (id < params.num_hash_table_slots) {
        point_hash_table_slots[id].state = SLOT_EMPTY;
        point_hash_table_slots[id].key = uvec2(0u);
        point_hash_table_slots[id].value = INVALID_ID;
    }

    if (id == 0u) {
        map_point_count_buffer.count = 0u;
        reset_all_counters_as_empty();
    }
}
