#version 450
#extension GL_GOOGLE_include_directive : require

layout(local_size_x = 256) in;

// ----- include -----
#include "../common/buffer_structures.inc"
// -------------------

layout(std430, set = 0, binding=0) coherent buffer ChunkHashTable { HashTableCounters chunk_hash_table_counters; ChunkHashTableSlot chunk_hash_table_slots[]; };
layout(std430, set = 0, binding=1) readonly buffer ChunkVoxels { VoxelData voxels[]; };
layout(std430, set = 0, binding=2) buffer Result { uint result; }; // 0 - fail, 1 - success

layout(push_constant) uniform CheckFootprintPushConstants {
    ivec4 u_chunk_dim;
    uint u_chunk_hash_table_size;

    uint u_voxels_per_chunk;

    uint u_pack_offset;
    uint u_pack_bits;

    ivec4 u_origin;
    uvec4 offset_count;

    uint max_step_up;
};

// ----- include -----
#include "../common/utils.inc"

#include "chunk_hash_table/common.inc"
#include "chunk_hash_table/lookup_remove.inc"
#include "chunk_pool/voxel_index.inc"
// -------------------

bool get_voxel(ivec3 world_pos, out VoxelData voxel)
{
    ivec3 chunk_pos = floor_div(world_pos, u_chunk_dim.xyz);
    ivec3 local_pos = world_pos - chunk_pos * u_chunk_dim.xyz;

    uvec2 key = pack_key_uvec2(
        chunk_pos,
        u_pack_offset,
        u_pack_bits
    );

    uint slot_id =
        chunk_hash_table_lookup_hash_table_slot_id(key, true);

    if (slot_id == INVALID_ID) {
        voxel.type_flags = 0u;
        voxel.color = 0u;
        return false;
    }

    uint chunk_id = chunk_hash_table_slots[slot_id].value;
    uint local_id = voxel_index(local_pos);
    uint global_id =
        chunk_id * u_voxels_per_chunk + local_id;

    voxel = voxels[global_id];
    return true;
}

void main() {
    uint x_offset = gl_GlobalInvocationID.x;
    uint y_offset = gl_GlobalInvocationID.y;
    uint z_offset = gl_GlobalInvocationID.z;

    if (x_offset >= offset_count.x) return;
    if (y_offset >= offset_count.y) return;
    if (z_offset >= offset_count.z) return;

    uint voxel_count_to_check = uint(max(int(max_step_up) + 1 - int(y_offset), 1));
    
    for (uint i = 0; i < voxel_count_to_check; i++) {
        ivec3 voxel_pos = u_origin.xyz + ivec3(x_offset, y_offset + i, z_offset);

        VoxelData voxel;

        if (!get_voxel(voxel_pos, voxel)) {
            return;
        }

        bool solid =
            (read_voxel_flags(voxel.type_flags) &
            VOXEL_VISABILITY_FLAG_BIT) != 0u;

        if (!solid) {
            return;
        }
    }

    atomicExchange(result, 0u);
}
