#version 450
#extension GL_GOOGLE_include_directive : require

layout(local_size_x = 256) in;

// ----- include -----
#include "../common/buffer_structures.inc"
// -------------------

layout(std430, set = 0, binding=0) coherent buffer ChunkHashTable { HashTableCounters chunk_hash_table_counters; ChunkHashTableSlot chunk_hash_table_slots[]; };
layout(std430, set = 0, binding=1) readonly buffer ChunkMetaBuf { ChunkMeta meta[]; };
layout(std430, set = 0, binding=2) buffer EnqueuedBuf { uint enqueued[]; };

layout(push_constant) uniform FillChunkHashTablePushConstants {
    uint u_max_chunks;
    uint u_chunk_hash_table_size;
    uint u_pack_bits;
    int u_pack_offset;
};

// ----- include -----
#include "../common/utils.inc"
#include "chunk_hash_table/common.inc"
#include "chunk_hash_table/lookup_remove.inc"
// -------------------

void main() {
    uint chunk_id = gl_GlobalInvocationID.x;
    if (chunk_id >= u_max_chunks) return;

    ChunkMeta chunk_meta = meta[chunk_id];
    if (chunk_meta.used == 0u) return;

    uvec2 key = uvec2(chunk_meta.key_lo, chunk_meta.key_hi);

    chunk_hash_table_set_slot_value(key, chunk_id);
}
