#version 450
#extension GL_GOOGLE_include_directive : require

layout(local_size_x = 256) in;

// ----- include -----
#include "../common/buffer_structures.inc"
// -------------------

layout(std430, set = 0, binding = 0) coherent buffer ChunkHashTable { HashTableCounters chunk_hash_table_counters; ChunkHashTableSlot chunk_hash_table_slots[]; };
layout(std430, set = 0, binding = 1) buffer ChunkVoxels { VoxelData voxels[]; };
layout(std430, set = 0, binding = 2) readonly buffer ToInflateListBuf { uint to_inflate_count; uint to_inflate_list[]; };
layout(std430, set = 0, binding = 3) buffer ChunkMetaBuf { ChunkMeta meta[]; };
layout(std430, set = 0, binding = 4) buffer EnqueuedBuf { uint enqueued[]; };

layout(push_constant) uniform InflateChunksPushConstants {
    ivec4 u_chunk_dim;
    uint u_chunk_hash_table_size;
    uint u_voxels_per_chunk;
    uint u_pack_offset;
    uint u_pack_bits;
    uint u_negative_x_inflation_size;
    uint u_positive_x_inflation_size;
    uint u_negative_y_inflation_size;
    uint u_positive_y_inflation_size;
    uint u_negative_z_inflation_size;
    uint u_positive_z_inflation_size;
};

// ----- include -----
#include "chunk_pool/read_voxels.inc"
// -------------------

shared uint shared_target_chunk_id;
shared ivec3 shared_target_chunk_pos;

uint inflation_flags_from_neighbor(uint target_chunk_id, ivec3 target_chunk_pos, ivec3 target_local_pos, ivec3 offset)
{
    bool success;
    VoxelData source_voxel = neighbor_voxel_data(
        target_chunk_id,
        target_chunk_pos,
        target_local_pos,
        offset,
        success
    );
    if (!success) return 0u;

    uint source_flags = read_voxel_flags(source_voxel.type_flags);
    if ((source_flags & VOXEL_VISABILITY_FLAG_BIT) == 0u) {
        return 0u;
    }

    return VOXEL_INFLATED_BIT |
        (source_flags & VOXEL_CURVATURE_LIMIT_EXCEEDED_BIT);
}

uint intersecting_inflation_flags(uint target_chunk_id, ivec3 target_chunk_pos, ivec3 target_local_pos)
{
    uint flags = inflation_flags_from_neighbor(target_chunk_id, target_chunk_pos, target_local_pos, ivec3(0));
    if ((flags & VOXEL_CURVATURE_LIMIT_EXCEEDED_BIT) != 0u) return flags;

    for (int x = 1; x <= int(u_negative_x_inflation_size); ++x) {
        flags |= inflation_flags_from_neighbor(target_chunk_id, target_chunk_pos, target_local_pos, ivec3(-x, 0, 0));
        if ((flags & VOXEL_CURVATURE_LIMIT_EXCEEDED_BIT) != 0u) return flags;
    }

    for (int x = 1; x <= int(u_positive_x_inflation_size); ++x) {
        flags |= inflation_flags_from_neighbor(target_chunk_id, target_chunk_pos, target_local_pos, ivec3(x, 0, 0));
        if ((flags & VOXEL_CURVATURE_LIMIT_EXCEEDED_BIT) != 0u) return flags;
    }

    for (int y = 1; y <= int(u_negative_y_inflation_size); ++y) {
        flags |= inflation_flags_from_neighbor(target_chunk_id, target_chunk_pos, target_local_pos, ivec3(0, -y, 0));
        if ((flags & VOXEL_CURVATURE_LIMIT_EXCEEDED_BIT) != 0u) return flags;
    }

    for (int y = 1; y <= int(u_positive_y_inflation_size); ++y) {
        flags |= inflation_flags_from_neighbor(target_chunk_id, target_chunk_pos, target_local_pos, ivec3(0, y, 0));
        if ((flags & VOXEL_CURVATURE_LIMIT_EXCEEDED_BIT) != 0u) return flags;
    }

    for (int z = 1; z <= int(u_negative_z_inflation_size); ++z) {
        flags |= inflation_flags_from_neighbor(target_chunk_id, target_chunk_pos, target_local_pos, ivec3(0, 0, -z));
        if ((flags & VOXEL_CURVATURE_LIMIT_EXCEEDED_BIT) != 0u) return flags;
    }

    for (int z = 1; z <= int(u_positive_z_inflation_size); ++z) {
        flags |= inflation_flags_from_neighbor(target_chunk_id, target_chunk_pos, target_local_pos, ivec3(0, 0, z));
        if ((flags & VOXEL_CURVATURE_LIMIT_EXCEEDED_BIT) != 0u) return flags;
    }

    return flags;
}

void main()
{
    uint voxel_id = gl_GlobalInvocationID.x;
    uint to_inflate_id = gl_GlobalInvocationID.y;
    if (to_inflate_id >= to_inflate_count) return;

    if (gl_LocalInvocationID.x == 0u) {
        shared_target_chunk_id = to_inflate_list[to_inflate_id];
        shared_target_chunk_pos = unpack_key_to_coord(
            uvec2(meta[shared_target_chunk_id].key_lo, meta[shared_target_chunk_id].key_hi),
            u_pack_offset,
            u_pack_bits
        );
    }

    barrier();

    if (voxel_id >= u_voxels_per_chunk) return;

    uint target_chunk_id = shared_target_chunk_id;
    uint target_global_voxel_id = target_chunk_id * u_voxels_per_chunk + voxel_id;

    uint target_type_flags = voxels[target_global_voxel_id].type_flags;
    uint target_type = read_voxel_type(target_type_flags);
    uint target_flags = read_voxel_flags(target_type_flags);

    ivec3 target_chunk_pos = shared_target_chunk_pos;
    ivec3 target_local_pos = local_voxel_pos_from_index(voxel_id);

    target_flags &= ~VOXEL_INFLATED_BIT;
    if ((target_flags & VOXEL_VISABILITY_FLAG_BIT) == 0u) {
        target_flags &= ~VOXEL_CURVATURE_LIMIT_EXCEEDED_BIT;
    }

    uint inflation_flags = intersecting_inflation_flags(target_chunk_id, target_chunk_pos, target_local_pos);
    target_flags |= inflation_flags;

    voxels[target_global_voxel_id].type_flags = pack_voxel_type_flags(target_type, target_flags);

    if (voxel_id == 0u) {
        atomicAnd(meta[target_chunk_id].dirty_flags, ~DIRTY_INFLATE_FLAG_BIT);
        atomicAnd(enqueued[target_chunk_id], ~DIRTY_INFLATE_FLAG_BIT);
    }
}
