#version 450
#extension GL_GOOGLE_include_directive : require

layout(local_size_x = 256) in;

// ----- include -----
#include "../common/buffer_structures.inc"
// -------------------

layout(std430, set = 0, binding=0) readonly buffer ReadableAllocationRetryList { uint readable_retry_list_counter; uint readable_retry_list[]; };
layout(std430, set = 0, binding=1) buffer WritableAllocationRetryList { uint writable_retry_list_counter; uint writable_retry_list[]; };

layout(std430, set = 0, binding=2) readonly buffer DirtyListBuf { uint dirty_count; uint dirty_list[]; };
layout(std430, set = 0, binding=3) readonly buffer DirtyQuadCountBuf { uint dirty_quad_count[]; };

layout(std430, set = 0, binding=4) readonly buffer ChunkMetaBuf { ChunkMeta meta[]; };
layout(std430, set = 0, binding=5) buffer ChunkMeshAllocLocalBuf { ChunkMeshAlloc chunk_alloc_local[]; }; 

layout(std430, set = 0, binding=6) coherent buffer BBHeads { uint bb_heads[]; };
layout(std430, set = 0, binding=7) coherent buffer BBState { uint bb_state[]; };
layout(std430, set = 0, binding=8) coherent buffer BBNodes  { Node bb_nodes[];  };
layout(std430, set = 0, binding=9) coherent buffer BBFreeNodesList  { uint bb_free_nodes_counter; uint bb_free_nodes_list[];  };
layout(std430, set = 0, binding=10) coherent buffer BBReturnedNodesList  { uint bb_returned_nodes_counter; uint bb_returned_nodes_list[]; };


layout(push_constant) uniform RetryMeshAllocPushConstants {
    uint bb_pages;
    uint bb_page_elements;
    uint bb_max_order;
    uint bb_quad_size;
    uint u_is_vb_phase;
};

// ----- include -----
#include "../common/utils.inc"

#define PREFIX bb
#include "../common/allocator/alloc_pages_impl.inc"
#undef PREFIX
// -------------------

bool is_vb_phase = u_is_vb_phase == 1u;

void main() {
    uint retry_id = gl_GlobalInvocationID.x;
    if (retry_id >= readable_retry_list_counter) return;
    
    uint dirty_idx = readable_retry_list[retry_id];
    uint chunk_id = dirty_list[dirty_idx];

    /*
        В теории здесь проверять не нужно, так как сюда такие dirty_idx попадть не должны
        Но пока оставим...
    */
    if (meta[chunk_id].used == 0u) {
        if (is_vb_phase){
            chunk_alloc_local[dirty_idx].v_startPage = INVALID_ID;
            chunk_alloc_local[dirty_idx].v_order = 0u;
            chunk_alloc_local[dirty_idx].needV = 0u;
        } else {
            chunk_alloc_local[dirty_idx].i_startPage = INVALID_ID;
            chunk_alloc_local[dirty_idx].i_order = 0u;
            chunk_alloc_local[dirty_idx].needI = 0u;
        }
        
        chunk_alloc_local[dirty_idx].is_valid = 1u;
        return;
    }

    uint quads = dirty_quad_count[dirty_idx];

    // Точно также сюда попадть не должен...
    if (quads == 0u) {
        if (is_vb_phase){
            chunk_alloc_local[dirty_idx].v_startPage = INVALID_ID;
            chunk_alloc_local[dirty_idx].v_order = 0u;
            chunk_alloc_local[dirty_idx].needV = 0u;
        } else {
            chunk_alloc_local[dirty_idx].i_startPage = INVALID_ID;
            chunk_alloc_local[dirty_idx].i_order = 0u;
            chunk_alloc_local[dirty_idx].needI = 0u;
        }
        
        chunk_alloc_local[dirty_idx].is_valid = 1u;
        return;
    }

    uint needB = quads * bb_quad_size;
    uint bPages = div_up_u32(needB, bb_page_elements);
    uint bOrder = ceil_log2_u32(bPages);

    uint bStart = bb_alloc_pages(bOrder);
    if (bStart == INVALID_ID) {
        uint idx = atomicAdd(writable_retry_list_counter, 1u);
        writable_retry_list[idx] = dirty_idx;
        return;
    }

    if (is_vb_phase) {
        chunk_alloc_local[dirty_idx].v_startPage = bStart;
        chunk_alloc_local[dirty_idx].v_order = bOrder;
        chunk_alloc_local[dirty_idx].needV = needB;
    } else {
        chunk_alloc_local[dirty_idx].i_startPage = bStart;
        chunk_alloc_local[dirty_idx].i_order = bOrder;
        chunk_alloc_local[dirty_idx].needI = needB;
    }

    chunk_alloc_local[dirty_idx].is_valid = 1u;
}
