#version 450
#extension GL_GOOGLE_include_directive : require

layout(local_size_x = 256, local_size_y = 1, local_size_z = 1) in;

#include "../common/buffer_structures.inc"
#include "utils.inc"

layout(std430, set = 0, binding = 0) readonly buffer LocalChunkMeshAllocBuf { ChunkMeshAlloc chunk_alloc_local[]; };
layout(std430, set = 0, binding = 1) buffer GlobalChunkMeshAllocBuf { ChunkMeshAlloc chunk_alloc_global[]; };
layout(std430, set = 0, binding = 2) readonly buffer DirtyListBuf { uint dirty_count; uint dirty_list[]; };
layout(std430, set = 0, binding = 3) buffer MeshBuffersStatusBuf { uint is_vb_full; uint is_ib_full; };
layout(std430, set = 0, binding = 4) buffer VBHeads { uint vb_heads[]; };
layout(std430, set = 0, binding = 5) buffer VBState { uint vb_state[]; };
layout(std430, set = 0, binding = 6) buffer VBNodes { Node vb_nodes[]; };
layout(std430, set = 0, binding = 7) buffer VBFreeNodesList { uint vb_free_nodes_counter; uint vb_free_nodes_list[]; };
layout(std430, set = 0, binding = 8) buffer VBReturnedNodesList { uint vb_returned_nodes_counter; uint vb_returned_nodes_list[]; };
layout(std430, set = 0, binding = 9) buffer IBHeads { uint ib_heads[]; };
layout(std430, set = 0, binding = 10) buffer IBState { uint ib_state[]; };
layout(std430, set = 0, binding = 11) buffer IBNodes { Node ib_nodes[]; };
layout(std430, set = 0, binding = 12) buffer IBFreeNodesList { uint ib_free_nodes_counter; uint ib_free_nodes_list[]; };
layout(std430, set = 0, binding = 13) buffer IBReturnedNodesList { uint ib_returned_nodes_counter; uint ib_returned_nodes_list[]; };

layout(push_constant) uniform VerifyMeshAllocationPushConstants {
    uint vb_max_order;
    uint ib_max_order;
};

#define PREFIX vb
#include "../common/allocator.inc"

#define PREFIX ib
#include "../common/allocator.inc"

void free_chunk_mesh(uint chunk_id) {
    ChunkMeshAlloc alloc = chunk_alloc_global[chunk_id];
    if (alloc.v_startPage != INVALID_ID) {
        vb_free_pages(alloc.v_startPage, alloc.v_order);
    }
    if (alloc.i_startPage != INVALID_ID) {
        ib_free_pages(alloc.i_startPage, alloc.i_order);
    }
}

void main() {
    uint dirty_id = gl_GlobalInvocationID.x;
    if (dirty_id >= dirty_count) {
        return;
    }

    if (is_vb_full != 1u && is_ib_full != 1u) {
        uint chunk_id = dirty_list[dirty_id];
        free_chunk_mesh(chunk_id);
        chunk_alloc_global[chunk_id] = chunk_alloc_local[dirty_id];
    }
}
