#version 450
#extension GL_GOOGLE_include_directive : require

layout(local_size_x = 256) in;

// // ----- include -----
#include "../common/buffer_structures.inc"
// // -------------------

// struct VoxelWrite {
//     ivec4 world_voxel; // xyz use, w unused
//     VoxelData voxel_data;
//     uint set_flags;
//     uint _pad1;
// };

struct PointInstance {
    vec4 position;
    vec4 color;
};

layout(std430, set = 0, binding = 0) readonly buffer SourcePointBuffer {
    PointInstance points[];
} source_point_buffer;

layout(std430, set = 0, binding = 1) buffer TargetVoxelWrites {
    uint count_voxel_writes;
    uint pad_[3u];
    VoxelWrite voxel_writes[];
} voxel_write_list;

layout(push_constant) uniform VoxelListFromPointCloudPushConstants {
    mat4 source_point_cloud_model;
    vec4 voxel_size;
    uint point_count;
    uint max_write_count;
};

float random01(uint value) {
    value ^= value >> 16u;
    value *= 0x7feb352du;
    value ^= value >> 15u;
    value *= 0x846ca68bu;
    value ^= value >> 16u;

    return float(value) / 4294967295.0;
}

void main() {
    uint point_id = gl_GlobalInvocationID.x;

    if (point_id >= point_count) return;
    if (point_id >= max_write_count) return;

    if (point_id == 0u) {
        voxel_write_list.count_voxel_writes = min(point_count, max_write_count);
    }

    vec3 world_pos = (source_point_cloud_model * source_point_buffer.points[point_id].position).xyz;
    vec3 local = world_pos / voxel_size.xyz;

    ivec4 voxel_pos = ivec4(ivec3(floor(local)), 1);

    VoxelData voxel_data;
    voxel_data.type_flags = pack_voxel_type_flags(1u, VOXEL_VISABILITY_FLAG_BIT);

    vec3 base_color = vec3(0.0, 98.0, 255.0);
    vec3 color = base_color * (0.5 + random01(point_id) * 0.5);
    uvec3 packed_color = uvec3(color);
    voxel_data.color = (packed_color.r << 24u) | (packed_color.g << 16u) | (packed_color.b << 8u) | 255u;

    voxel_write_list.voxel_writes[point_id].world_voxel = voxel_pos;
    voxel_write_list.voxel_writes[point_id].voxel_data = voxel_data;
    voxel_write_list.voxel_writes[point_id].set_flags = OVERWRITE_BIT;
    voxel_write_list.voxel_writes[point_id]._pad1 = 0u;
}
