// Template-like Vulkan GLSL include file.
// Expected before include:
//   HASH_TABLE_PREFIX(NAME)
//   COUNTER_TYPE_NAME: empty / occupied / tomb
//   TABLE_COUNTERS: instance name of HashTableCounters, e.g. counters
//   COUNT_TABLE_COUNTERS

#ifndef COUNTER_TYPE_NAME
#error "COUNTER_TYPE_NAME must be defined before including hash_table_counters_impl.comp"
#endif

void HASH_TABLE_PREFIX(HT_CAT3(add_, COUNTER_TYPE_NAME, _counter))(uint slot_id, uint add_value) {
    uint counter_id = slot_id % COUNT_TABLE_COUNTERS;
    atomicAdd(TABLE_COUNTERS.HT_CAT(count_, COUNTER_TYPE_NAME)[counter_id], add_value);
}

uint HASH_TABLE_PREFIX(HT_CAT3(reduce_read_, COUNTER_TYPE_NAME, _counter))() {
    uint counter = 0u;

    for (uint i = 0u; i < COUNT_TABLE_COUNTERS; i++) {
        counter += TABLE_COUNTERS.HT_CAT(count_, COUNTER_TYPE_NAME)[i];
    }

    return counter;
}

#undef COUNTER_TYPE_NAME
